apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: amrkedra/flask-app:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

        envFrom:
        - configMapRef:
            name: configmap
        ports:
        - containerPort: 5000
          name: flask-app
      imagePullSecrets:
      - name: mysecrets


---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  selector:
    app: flask-app
  type: cl
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30005
