apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flask
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: flask.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 80
  tls:
  - hosts:
    - flask.app
    secretName: flask-app-tls
