apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
  namespace: default
type: kubernetes.io/dockerconfigjson
data: #my dockerhub-secrets
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXMXlhMlZrY21FNlFXNHdNSE5oUURJd01Uaz0iLAoJCQkiZW1haWwiOiAiYW1ya2VkcmEuMTk5M0BnbWFpbC5jb20iCgkJfSwKCQkicmVnaXN0cnktMS5kb2NrZXIuaW8iOiB7CgkJCSJhdXRoIjogIllXMXlhMlZrY21FNlFXNHdNSE5oUURJd01Uaz0iLAoJCQkiZW1haWwiOiAiYW1ya2VkcmEuMTk5M0BnbWFpbC5jb20iCgkJfQoJfQp9
