version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
    - "80:80"
    - "443:443" # Optional: For HTTPS
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    # - /home/amr-kedra/Full-DevOps-Project/compose/nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/amrkedra/Full-DevOps-Project/compose/certs:/etc/nginx/certs:ro
    networks:
    - nginx-proxy

  # nginx-proxy-manager:
  #   image: jc21/nginx-proxy-manager:latest
  #   ports:
  #   - "81:81" # Web interface
  #   - "443:443" # Optional: For HTTPS
  #   volumes:
  #   - ./data:/data
  #   - ./letsencrypt:/etc/letsencrypt
  #   networks:
  #   - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge
