version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
    - "80:80"
    - "443:443" # Optional: For HTTPS
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /home/amrkedra/Full-DevOps-Project/compose/certs:/etc/nginx/certs:ro # For SSL certs if you're using them
    networks:
    - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge
